import Head from 'next/head';
import { AppType } from 'next/app';

import { Layout } from '../components/Layout';

import '../styles/globals.scss';

const MyApp: AppType = ({ Component, pageProps }) => (
  <>
    <Head>
      <title>Sportuj Spolu</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <Component {...pageProps} />
    </Layout>
  </>
);

export default MyApp;
